language: node_js
sudo: false
node_js:
  - 8
  - 10
  - 11
os:
  - windows
  - linux
  - osx
addons:
    firefox: latest
    chrome: stable
install:
  - yarn install
script:
    - yarn test -- --verbose
cache: yarn
